[theme]
theme = "ctp-mocha"
overrides = { idle_bg = "#1e1e2e", idle_fg = "#cdd6f4" }

[icons]
icons = "material-nf"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
mappings = { "English (US)" = "English", "Russian" = "Russian" }

[[block]]
block = "custom"
command = "bluetoothctl show | grep -q 'Powered: yes' && echo '󰂯' || echo '󰂲'"
interval = "once"
signal = 1

[[block]]
block = "temperature"
format = " $icon $max "
chip = "coretemp-isa-*"
interval = 10

[[block]]
block = "memory"
format = " $icon $mem_used_percents "
warning_mem = 80
critical_mem = 95
interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $icon $available "
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = " $icon $ssid $signal_strength "
missing_format = " $icon down "
interval = 5

[[block]]
block = "sound"
format = " $icon $volume "
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "backlight"
format = " $icon $brightness "

[[block]]
block = "battery"
format = " $icon $percentage "
missing_format = ""
full_format = " $icon full "
charging_format = " $icon $percentage+ "

[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%a %d/%m %R') "
